"""empty message

Revision ID: 05eef1e3e08b
Revises: c2080f4177c9
Create Date: 2025-02-20 18:42:50.329715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eef1e3e08b'
down_revision = 'c2080f4177c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        #batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint('unique_email_constraint', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_email_constraint', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###